# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=255)),
                ('num_sql_queries', models.IntegerField(default=0)),
            ],
        ),
    ]
