# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestprofile',
            name='num_sql_joins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestprofile',
            name='sql_query_time',
            field=models.FloatField(default=0),
        ),
    ]
